// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFJgQd6l7wDNV1VgWKTY562103RMOxgoI',
    appId: '1:291708441514:web:c21b7b744a876ee3ddd1d3',
    messagingSenderId: '291708441514',
    projectId: 'sleep-baeba',
    authDomain: 'sleep-baeba.firebaseapp.com',
    storageBucket: 'sleep-baeba.appspot.com',
    measurementId: 'G-VNHS14Z98C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZf_bRXk-nuWrIvsgFbOjD9ECTSv9zZ2Y',
    appId: '1:291708441514:android:40494cf6f535401addd1d3',
    messagingSenderId: '291708441514',
    projectId: 'sleep-baeba',
    storageBucket: 'sleep-baeba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB483AEDxpz9Zw5x_PWDuqd26xJPqwqPNU',
    appId: '1:291708441514:ios:b42ee712b413fbafddd1d3',
    messagingSenderId: '291708441514',
    projectId: 'sleep-baeba',
    storageBucket: 'sleep-baeba.appspot.com',
    iosBundleId: 'com.example.appLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB483AEDxpz9Zw5x_PWDuqd26xJPqwqPNU',
    appId: '1:291708441514:ios:bacf9334e16befadddd1d3',
    messagingSenderId: '291708441514',
    projectId: 'sleep-baeba',
    storageBucket: 'sleep-baeba.appspot.com',
    iosBundleId: 'com.example.appLogin.RunnerTests',
  );
}
